DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), LASTNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    ID_AUTHOR BIGINT,
    ID_GENRE BIGINT,
    foreign key (ID_AUTHOR) references AUTHORS(ID),
    foreign key (ID_GENRE) references GENRES(ID)
  );

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ID_BOOK BIGINT,
    TEXT VARCHAR(1000),
    USER_NAME VARCHAR(255),
    foreign key (ID_BOOK) references BOOKS(ID)
  );