DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, NAME VARCHAR(255), LASTNAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    ID_AUTHOR BIGINT,
    ID_GENRE BIGINT,
    foreign key (ID_AUTHOR) references AUTHORS(ID),
    foreign key (ID_GENRE) references GENRES(ID)
  );